name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened
  schedule:
    - cron: '0 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          issue-comment: 'PalorderSoftWorks does not accept issues on this repository currently.'
          pr-comment: 'PalorderSoftWorks does not accept pull requests on this repository currently.'
