name: MSBuild WDK Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: "EzAntiAntiCheat.sln"
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      # 3. Install latest WDK silently
      - name: Install latest WDK silently
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $wdkInstaller = "$env:TEMP\WDKsetup.exe"
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2128854" -OutFile $wdkInstaller
          Start-Process -FilePath $wdkInstaller -ArgumentList "/quiet" -Wait
          
          # WDK installs by default in Program Files (x86)
          $wdkPath = "C:\Program Files (x86)\Windows Kits\10"
          if (-not (Test-Path $wdkPath)) { throw "WDK installation failed" }
          Write-Host "WDK installed at $wdkPath"
          
          # Export paths for MSBuild
          echo "WDKContentRoot=$wdkPath" >> $env:GITHUB_ENV
          echo "WDK_INCLUDE=$wdkPath\Include" >> $env:GITHUB_ENV

      # 4. Restore NuGet packages
      - name: Restore NuGet packages
        working-directory: ${{ github.workspace }}
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      # 5. Build solution with MSBuild
      - name: Build with MSBuild
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          msbuild ${{ env.SOLUTION_FILE_PATH }} `
            /m `
            /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
            /p:Platform=${{ env.BUILD_PLATFORM }} `
            /p:PreferredToolArchitecture=x64 `
            /p:WDKContentRoot=$env:WDKContentRoot `
            /p:AdditionalIncludeDirectories="$env:WDK_INCLUDE\km;$env:WDK_INCLUDE\shared" `
            /verbosity:minimal

      # 6. Upload built artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EzAntiAntiCheat-Build
          path: |
            ${{ github.workspace }}/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_CONFIGURATION }}/*.sys
            ${{ github.workspace }}/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_CONFIGURATION }}/*.exe
